---

- name: Install ssh key certs from all hosts
  hosts: both 
  tasks:

    - name: Write the new host key to known hosts
      connection: local
      shell: "ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts"

