---

- name: Playbook for all hosts
  hosts: both 
  tasks:

    - name: Write the new host key to known hosts
      connection: local
      shell: "ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts"

    - name: Apt update
      become: yes
      apt:
        update_cache: yes
      register: apt_status
      until: apt_status is success
      delay: 6
      retries: 10

    - name: Apt upgrade
      become: yes
      become_method: sudo
      apt:
        upgrade: 'yes'
        cache_valid_time: 86400
      register: apt_status
      until: apt_status is success
      delay: 6
      retries: 10

